package edu.utap.hex.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase demands an empty constructor, so all fields must be optional
data class ChatRow(
    var name: String? = null,
    var ownerUid: String? = null,
    var message: String? = null,
    var pictureUUID: String? = null,
    // Allows us to replay chat while replaying game
    var moveNumber: Int = 0,
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
