package edu.utap.hex.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

// Firebase demands an empty constructor, so all fields must be optional
data class FirestoreGame(
    var boardDim : Int = 0,
    var firstPlayerUid : String = "",
    // Red player, then blue
    // I do this because firestore query has limited support for OR
    // and I want to fetch my games, whether I am red or blue
    var playerUidList : List<String> = listOf(),
    var playerNameList : List<String> = listOf(),
    var moves : List<Int> = listOf(),
    @ServerTimestamp
    val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, set by us, used as primary key
    var firestoreID: String = ""
)